color0 #181211
color1 #ffb4ab
color2 #ffb5a2
color3 #e4beb5
color4 #c7cb89
color5 #ffb5a2
color6 #e4beb5
color7 #ece0dd
color8 #9f8d88
color9 #ffb4ab
color10 #ffb5a2
color11 #e4beb5
color12 #c7cb89
color13 #ffb5a2
color14 #e4beb5
color15 #ece0dd

cursor                #ece0dd
cursor_text_color     #181211
background            #181211
foreground            #ece0dd
selection_foreground  #d7c2bd
selection_background  #524340
active_border_color   #ffb5a2
inactive_border_color #524340
url_color             #ffb5a2

active_tab_foreground   #512317
active_tab_background   #ffb5a2
inactive_tab_foreground #d7c2bd
inactive_tab_background #524340
cursor_trail_color      #d7c2bd
